app = "arg_bot"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
BOT_TOKEN = "bot_token_secret"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    type = "connections"
    soft_limit = 20
    hard_limit = 25

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443
