name: Deploy Bots to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - arg-bot
          - manager-bot

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Write dynamic Procfile for ${{ matrix.service }}
        run: |
          if [ "${{ matrix.service }}" = "arg-bot" ]; then
            echo "web: PYTHONPATH=src python -m runners.run_arg" > Procfile
          elif [ "${{ matrix.service }}" = "manager-bot" ]; then
            echo "web: PYTHONPATH=src python -m runners.run_manager" > Procfile
          fi
          cat Procfile

      - name: Deploy ${{ matrix.service }} to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          CI: false
        run: |
          railway up --service ${{ matrix.service }}
